# Use the official tiangolo/uvicorn-gunicorn-fastapi image as base
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# Set the working directory in the container
WORKDIR /chatbot

# Copy the requirements file into the container
COPY chatbot/requirements.txt /chatbot/

# Install the dependencies
RUN pip install -r /chatbot/requirements.txt

# Copy the application code into the container
COPY chatbot /chatbot/

# Specify the command to run the FastAPI application using uvicorn
CMD ["uvicorn", "chat:app", "--host", "0.0.0.0", "--port", "8000"]